name: flutter_application_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  image_picker: ^0.8.1+1
  tflite: ^1.1.2
  
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  introduction_screen: ^2.1.0
  bordered_text: ^2.0.0
  curved_navigation_bar: ^1.0.3
  getwidget: ^2.0.4
  carousel_slider: ^4.0.0
  animated_bottom_navigation_bar: ^0.3.2
  gradient_app_bar: ^0.1.3
  smooth_page_indicator: ^1.0.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
flutter:
  uses-material-design: true
  assets:
    
    - assets/intro.png
    - assets/logo app.png
    - assets/no1.jpg
    - assets/no2.jpg
    - assets/no3.jpg
    - assets/no4.jpg
    - assets/no5.jpg
    - assets/no6.jpg
    - assets/no7.jpg
    - assets/no8.jpg
    - assets/no9.jpg
    - assets/labels.txt
    - assets/model.tflite
    - assets/animated-car-image-0112.gif
    - assets/gif-3.gif
    - assets/use1.png
    - assets/use2.png
    - assets/use3.png
    - assets/use4.png
    - assets/use5.png
    - assets/use6.png
    - assets/use7.png
    - assets/use8.png
    - assets/use9.png
    - assets/offroadexamcar.png
    - assets/use10.png
    - assets/use11.png
    - assets/001.png
    - assets/004.png
    - assets/006.png
    - assets/014.png
    - assets/016.png
    - assets/018.png
    - assets/b1.jpg
    - assets/b2.jpg
    - assets/b3.jpg
    - assets/b4.jpg
    - assets/b5.jpg
    - assets/b6.jpg
    - assets/b7.jpg
    - assets/b8.jpg
    - assets/a1.jpg
    - assets/a2.jpg
    - assets/a3.jpg
    - assets/a4.jpg
    - assets/a5.jpg
    - assets/a6.jpg
    - assets/o1.png
    - assets/o2.jpg
    - assets/o3.jpg
    - assets/o4.jpg
    - assets/o5.jpg
    - assets/datacar/data.json
    - assets/11.jpg
    - assets/12.jpg
    - assets/13.jpg
    - assets/14.jpg
    - assets/16.jpg
    - assets/17.jpg
    - assets/ex1.jpg
    - assets/ex2.jpg
    - assets/ex3.jpg
    - assets/ex4.jpg
    - assets/BG1.jpg
    - assets/BG2.jpg
    - assets/BG3.jpg
    - assets/BG4.jpg
  fonts:
    - family: Shizuru
      fonts:
        - asset: fonts/Shizuru-Regular.ttf
          weight: 400 
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
          weight: 400 
    - family: SansProsemiBold
      fonts:
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-Regular.ttf
          weight: 400
    - family : Chakra
      fonts :
        - asset : fonts/ChakraPetch-Light.ttf
  
  