name: flutter_application_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.8.6
  tflite: ^1.1.2
  cupertino_icons: ^0.1.2
  introduction_screen: ^2.1.0
  bordered_text: ^2.0.0
  curved_navigation_bar: ^1.0.3
  getwidget: ^2.0.4
  carousel_slider: ^4.0.0
  animated_bottom_navigation_bar: ^0.3.2
  gradient_app_bar: ^0.1.3
  smooth_page_indicator: ^1.0.0+2
  http: ^0.13.4
  size: ^1.0.5+1
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_dotenv: ^5.0.2
  image_cropper: ^3.0.1
  path_provider: ^2.0.11
flutter_icons:
  android: ture
  image_path: 'logomyapp/logo app.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/photo/
    - assets/BG/
    - assets/Badimage/
    - assets/CarB/
    - assets/CarF/
    - assets/EX/
    - assets/Goodimage/
    - assets/No 9/
    - assets/NoOrigincar/
    - assets/imgdatacar/
    - assets/intro.png
    - assets/logo app.png
    - assets/labels.txt
    - assets/model.tflite
    - assets/modelf.tflite
    - assets/modelr.tflite
    - assets/animated-car-image-0112.gif
    - assets/gif-3.gif
    - assets/carsearch.png
    - assets/carcare.png
    - assets/carexam.png
    - assets/logowaitupdate.png
    - .env
    #- assets/BG2.jpg

    - assets/datacar/data.json

  fonts:
    - family: Shizuru
      fonts:
        - asset: fonts/Shizuru-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
          weight: 400
    - family: SansProsemiBold
      fonts:
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-Regular.ttf
          weight: 400
    - family: Chakra
      fonts:
        - asset: fonts/ChakraPetch-Light.ttf
